# Generated by Django 2.1.7 on 2019-03-03 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechToText', '0006_auto_20190303_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='UploadedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
