# Generated by Django 2.1.7 on 2019-03-05 16:07

import SpeechToText.models
import SpeechToText.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeechToText', '0007_auto_20190303_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Content',
            field=models.FileField(upload_to=SpeechToText.models.scramble_uploaded_filename, validators=[SpeechToText.validators.validate_file_extension], verbose_name='UploadedFiles'),
        ),
    ]
